### PR TITLE
fix spelling errors

### PR DESCRIPTION
**Pull request by doctorcolossus**

### CODE REVIEW

**Review by GregDews — APPROVED** [review]

**Review by MattHurt — APPROVED** [review]
I approve

**Review by MattHurt — APPROVED** [review]

**Review by MattHurt — APPROVED** [review]
Good

**Review by GregDews — APPROVED** [review]

**Review by MattHurt — APPROVED** [review]

**Comment by doctorcolossus** [comment]
> I approve

But how can I know that you are the real KnifeHand?

**Review by danieljlepiscopo — APPROVED** [review]
Approved. All speed ahead!

**Pull request merged**
